// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOutlookAccounts(arg1) {
  return window['go']['main']['App']['AddOutlookAccounts'](arg1);
}

export function AddProxyEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProxyEntry'](arg1, arg2, arg3);
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearOutlookAccounts() {
  return window['go']['main']['App']['ClearOutlookAccounts']();
}

export function ClearRegisteredOutlookAccounts() {
  return window['go']['main']['App']['ClearRegisteredOutlookAccounts']();
}

export function DeleteKiroCliAccount(arg1) {
  return window['go']['main']['App']['DeleteKiroCliAccount'](arg1);
}

export function DeleteOutlookAccount(arg1) {
  return window['go']['main']['App']['DeleteOutlookAccount'](arg1);
}

export function DeleteProxyEntry(arg1) {
  return window['go']['main']['App']['DeleteProxyEntry'](arg1);
}

export function DeleteSuspendedKiroCliAccounts(arg1) {
  return window['go']['main']['App']['DeleteSuspendedKiroCliAccounts'](arg1);
}

export function DetectProxy(arg1) {
  return window['go']['main']['App']['DetectProxy'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetCloudMailConfigs() {
  return window['go']['main']['App']['GetCloudMailConfigs']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMoeMailConfigs() {
  return window['go']['main']['App']['GetMoeMailConfigs']();
}

export function GetOSLanguage() {
  return window['go']['main']['App']['GetOSLanguage']();
}

export function GetOutlookAccounts() {
  return window['go']['main']['App']['GetOutlookAccounts']();
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetProxy() {
  return window['go']['main']['App']['GetProxy']();
}

export function GetRegisterLogPath() {
  return window['go']['main']['App']['GetRegisterLogPath']();
}

export function GetResultOutputDir() {
  return window['go']['main']['App']['GetResultOutputDir']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptionLink(arg1, arg2) {
  return window['go']['main']['App']['GetSubscriptionLink'](arg1, arg2);
}

export function GetSubscriptionPlans(arg1) {
  return window['go']['main']['App']['GetSubscriptionPlans'](arg1);
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function ImportKiroCliAccount(arg1) {
  return window['go']['main']['App']['ImportKiroCliAccount'](arg1);
}

export function ImportOutlookFile(arg1) {
  return window['go']['main']['App']['ImportOutlookFile'](arg1);
}

export function KiroCliStartCommand() {
  return window['go']['main']['App']['KiroCliStartCommand']();
}

export function ListProxyPool() {
  return window['go']['main']['App']['ListProxyPool']();
}

export function LoadKiroCliAccounts() {
  return window['go']['main']['App']['LoadKiroCliAccounts']();
}

export function LoadOutputAccounts() {
  return window['go']['main']['App']['LoadOutputAccounts']();
}

export function LogoutLicense() {
  return window['go']['main']['App']['LogoutLicense']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PrecheckKiroCliAccount(arg1) {
  return window['go']['main']['App']['PrecheckKiroCliAccount'](arg1);
}

export function ResetDataDir() {
  return window['go']['main']['App']['ResetDataDir']();
}

export function ResetFingerprintCache() {
  return window['go']['main']['App']['ResetFingerprintCache']();
}

export function ResetProxy() {
  return window['go']['main']['App']['ResetProxy']();
}

export function ResetResultOutputDir() {
  return window['go']['main']['App']['ResetResultOutputDir']();
}

export function SaveCloudMailConfigs(arg1) {
  return window['go']['main']['App']['SaveCloudMailConfigs'](arg1);
}

export function SaveMoeMailConfigs(arg1) {
  return window['go']['main']['App']['SaveMoeMailConfigs'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectOutlookFile() {
  return window['go']['main']['App']['SelectOutlookFile']();
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['main']['App']['SetProxy'](arg1);
}

export function SetResultOutputDir(arg1) {
  return window['go']['main']['App']['SetResultOutputDir'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function TestCloudMailConnection(arg1) {
  return window['go']['main']['App']['TestCloudMailConnection'](arg1);
}

export function TestMoeMailConnection(arg1) {
  return window['go']['main']['App']['TestMoeMailConnection'](arg1);
}

export function TestProxyEntry(arg1) {
  return window['go']['main']['App']['TestProxyEntry'](arg1);
}

export function UpdateProxyEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProxyEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function VerifyLicense(arg1) {
  return window['go']['main']['App']['VerifyLicense'](arg1);
}
