// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {email} from '../models';
import {task} from '../models';

export function AddOutlookAccounts(arg1:string):Promise<Record<string, any>>;

export function AddProxyEntry(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function CancelUpdate():Promise<Record<string, any>>;

export function CheckLicense():Promise<Record<string, any>>;

export function CheckUpdate():Promise<Record<string, any>>;

export function ClearOutlookAccounts():Promise<Record<string, any>>;

export function ClearRegisteredOutlookAccounts():Promise<Record<string, any>>;

export function DeleteKiroCliAccount(arg1:string):Promise<Record<string, any>>;

export function DeleteOutlookAccount(arg1:string):Promise<Record<string, any>>;

export function DeleteProxyEntry(arg1:string):Promise<Record<string, any>>;

export function DeleteSuspendedKiroCliAccounts(arg1:Array<string>):Promise<Record<string, any>>;

export function DetectProxy(arg1:string):Promise<proxy.Info>;

export function DownloadUpdate():Promise<Record<string, any>>;

export function GetCloudMailConfigs():Promise<Array<email.CloudMailConfig>>;

export function GetDataDir():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLicenseInfo():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetMoeMailConfigs():Promise<Array<email.MoeMailConfig>>;

export function GetOSLanguage():Promise<string>;

export function GetOutlookAccounts():Promise<Array<Record<string, any>>>;

export function GetOverview():Promise<Record<string, any>>;

export function GetProxy():Promise<string>;

export function GetRegisterLogPath():Promise<string>;

export function GetResultOutputDir():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function GetSubscriptionLink(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetSubscriptionPlans(arg1:string):Promise<Record<string, any>>;

export function GetTaskStatus():Promise<Record<string, any>>;

export function ImportKiroCliAccount(arg1:string):Promise<Record<string, any>>;

export function ImportOutlookFile(arg1:string):Promise<Record<string, any>>;

export function KiroCliStartCommand():Promise<string>;

export function ListProxyPool():Promise<Array<proxy.PoolEntry>>;

export function LoadKiroCliAccounts():Promise<Record<string, any>>;

export function LoadOutputAccounts():Promise<Record<string, any>>;

export function LogoutLicense():Promise<Record<string, any>>;

export function OpenURL(arg1:string):Promise<void>;

export function PrecheckKiroCliAccount(arg1:string):Promise<Record<string, any>>;

export function ResetDataDir():Promise<Record<string, any>>;

export function ResetFingerprintCache():Promise<Record<string, any>>;

export function ResetProxy():Promise<Record<string, any>>;

export function ResetResultOutputDir():Promise<Record<string, any>>;

export function SaveCloudMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SaveMoeMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function SelectOutlookFile():Promise<string>;

export function SetDataDir(arg1:string):Promise<Record<string, any>>;

export function SetLanguage(arg1:string):Promise<Record<string, any>>;

export function SetProxy(arg1:string):Promise<Record<string, any>>;

export function SetResultOutputDir(arg1:string):Promise<Record<string, any>>;

export function StartTask(arg1:task.StartTaskRequest):Promise<Record<string, any>>;

export function StopTask():Promise<Record<string, any>>;

export function TestCloudMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestMoeMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestProxyEntry(arg1:string):Promise<proxy.Info>;

export function UpdateProxyEntry(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<Record<string, any>>;

export function VerifyLicense(arg1:string):Promise<Record<string, any>>;
